module.exports = [
  { name: '21-10-18_s3rl-pack_alice', author: 'Alice', title: 'S3RL Pack' },
  { name: '21-10-15_ajr-music-pack_reddigamer', author: 'ReddiGamer', title: 'AJR Music Pack' },
  { name: '21-10-14_heavy-halloween_nitronikexe', author: 'nitronik.exe', title: 'Heavy Halloween' },
  { name: '21-10-02_arknights-2nd-anniversary-song-pack_joetastic', author: 'Joetastic', title: 'Arknights 2nd Anniversary Song Pack' },
  { name: '21-09-20_persona-25th-anniversary-song-pack_joetastic', author: 'Joetastic', title: 'Persona 25th Anniversary Song Pack' },
  { name: '21-07-08_dancerush-stardom-feet-saber-map-pack_wolfiebeat', author: 'WolfieBeat', title: 'DANCERUSH STARDOM Feet Saber Map Pack' },
  { name: '21-09-08_one-month-wonders-vol-1_beatmappingserver', author: 'BeatMappingServer', title: 'One-Month-Wonders Vol. 1' },
  { name: '21-08-17_wongys-absolute-bangers-vol-1_wngdav', author: 'Wngdav', title: 'Wongy\'s Absolute Bangers Vol. 1' },
  { name: '21-07-25_angel-beats-girldemo-map-pack_shanman', author: 'Shan_Man', title: 'Angel Beats! (GirlDeMo) Map Pack' },
  { name: '21-07-15_kuuro-music-pack_timeweaver', author: 'Timeweaver', title: 'KUURO Music Pack' },
  { name: '21-07-08_electro-swing-pack_nixie-korten', author: 'Nixie Korten', title: 'Electro Swing Pack' },
  { name: '21-07-01_pixel-terror-pack_alphabeat', author: 'Alphabeat', title: 'Pixel Terror Pack' },
  { name: '21-07-01_pixels-anime-collection_pixelboom', author: 'PixelBoom', title: 'Pixel\'s Anime Collection' },
  { name: '21-06-25_diamonds-in-the-rough-vol-2_helen-carnate', author: 'Helen Carnate', title: 'Diamonds in the Rough Vol. 2' },
  { name: '21-06-19_friday-night-funkin-pack_bobbie', author: 'Bobbie', title: 'Friday Night Funkin\' Pack' },
  { name: '21-06-01_noodlepride_ramen-noodle', author: 'Ramen Noodle', title: 'NoodlePride' },
  { name: '21-05-26_wish-upon-a-blackstar-map-pack_nitronikexe', author: 'nitronik.exe', title: 'Wish Upon A Blackstar Map Pack' },
  { name: '21-05-17_persona-dancing-in-vr-song-pack_joetastic', author: 'Joetastic', title: 'Persona: Dancing in VR Song Pack' },
  { name: '21-05-12_the-mello-pack_xavier', author: '[Xavier]', title: 'The Mello Pack' },
  { name: '21-05-08_fitbeat-map-pack_alice', author: 'Alice', title: 'Fitbeat Map Pack' },
  { name: '21-04-08_noodlejams-vol-1_skeelie', author: 'Skeelie', title: 'NoodleJams Vol. 1' },
  { name: '21-03-30_one-direction-midnight-memories-music-pack_alekcake', author: 'AlekCake', title: 'One Direction: Midnight Memories Music Pack' },
  { name: '21-03-29_2000s-rock-music-pack_bytrius', author: 'Various Mappers', title: '2000’s Rock Music Pack' },
  { name: '21-02-17_kda-all-out_sotarks', author: 'Sotarks', title: 'K/DA ALL OUT' },
  { name: '21-02-05_moms-maps_beastsaber', author: 'The BeastSaber Curation Team', title: 'Mom\'s Maps' },
  { name: '21-01-15_symphonic-metal-pack_cyrix', author: 'Cyrix, Wyxi, Hamsta, MrBlueSku', title: 'Symphonic Metal Pack' },
  { name: '21-01-07_diamonds-in-the-rough_helen-carnate', author: 'Helen Carnate', title: 'Diamonds in the Rough' },
  { name: '21-01-05_myrne-music-pack_pixelguy', author: 'Pixelguy', title: 'MYRNE Music Pack' },
  { name: '21-01-01_curators-picks-of-2020_beastsaber', author: 'The BeastSaber Curation Team', title: 'Curators\' Picks of 2020' },
  { name: '20-12-24_2020-bsmg-christmas-contest_bsmg', author: 'BSMG', title: '2020 BSMG Christmas Contest' },
  { name: '20-11-20_noodle-remaster-ost-2_pixelguy', author: 'Pixelguy', title: 'Noodle Remaster OST 2' },
  { name: '20-11-15_post-human-survival-horror_bytrius', author: 'Bytrius', title: 'POST HUMAN: SURVIVAL HORROR' },
  { name: '20-11-11_best-k-pop-maps-vol-6_bloodcloak', author: 'Bloodcloak', title: 'Best K-Pop Maps Vol. 6' },
  { name: '20-11-07_22-7-anime-soundtrack-volume-2_joetastic', author: 'Joetastic', title: '22/7 Anime Soundtrack Vol. 2' },
  { name: '20-10-29_noodleween-vol-2_ramen-noodle', author: 'Ramen Noodle', title: 'Noodleween Vol. 2' },
  { name: '20-10-29_2020-bsmg-halloween-contest_bsmg', author: 'BSMG', title: '2020 BSMG Halloween Contest' },
  { name: '20-10-27_rwby-song-pack_joetastic', author: 'Joetastic', title: 'RWBY Song Pack' },
  { name: '20-10-23_starcade-arcade-song-pack_joetastic', author: 'Joetastic', title: 'Starcade Arcade Song Pack' },
  { name: '20-10-23_code-pandorum-map-pack_nitronik-lethrial', author: 'Nitronik (& Lethrial)', title: 'Code:Pandorum Map Pack' },
  { name: '20-10-18_aquas-almighty-anime-song-pack_joetastic', author: 'Joetastic', title: 'Aqua’s Almighty Anime Song Pack' },
  { name: '20-10-13_little-shop-of-horrors-the-playlist_techbutterfly', author: 'TechButterfly', title: 'Little Shop of Horrors The Playlist' },
  { name: '20-10-01_pickletech-halloween-map-pack_techbutterfly', author: 'TechButterfly', title: 'PickleTech Halloween Map Pack' },
  { name: '20-09-20_sword-art-online-song-pack_joetastic', author: 'Joetastic', title: 'Sword Art Online Song Pack' },
  { name: '20-09-18_kshmr-music-pack_nitronikexe', author: 'nitronikexe', title: 'KSHMR Music Pack' },
  { name: '20-09-10_noodlegames-vol-2_skeelie', author: 'Skeelie', title: 'NoodleGames Vol. 2' },
  { name: '20-09-06_marshmello-pack_alphabeat', author: 'Alphabeat', title: 'Marshmello Pack' },
  { name: '20-09-01_idolmaster-songs-vol-2_joetastic', author: 'Joetastic', title: 'iDOLM@STER Songs Vol. 2' },
  { name: '20-08-31_extra-sensory_total-bs', author: 'TotalBS', title: 'Extra Sensory' },
  { name: '20-08-30_fall-guys-pack_model-citizens', author: 'Model Citizens', title: 'Fall Guys Pack' },
  { name: '20-08-16_future-funk-pack_etan', author: 'ETAN', title: 'Future Funk Pack' },
  { name: '20-08-07_toaru-kagaku-no-railgun-opening-song-pack_joetastic', author: 'Joetastic', title: 'Toaru Kagaku no Railgun Opening Song Pack' },
  { name: '20-08-01_arknights-song-pack_joetastic', author: 'Joetastic', title: 'Arknights Song Pack' },
  { name: '20-07-17_pegboard-nerds-music-pack_alphabeat', author: 'Pixelguy', title: '-Alphabeat- Pegboard Nerds Music Pack' },
  { name: '20-07-10_aquas-god-tier-anime-movie-song-pack_joetastic', author: 'Joetastic', title: 'Aqua\'s God Tier Anime Movie Song Pack' },
  { name: '20-06-27_22-7-soundtrack-vol-1_joetastic', author: 'Joetastic', title: '22/7 Soundtrack Vol. 1' },
  { name: '20-06-24_bloq-busters-vol-5-overdrive_bloq-busters', author: 'Bloq Busters', title: 'Overdrive (Bloq Busters Vol. 5)' },
  { name: '20-06-18_joetastic-joestars-jojos-bizarre-adventure-song-pack_joetastic', author: 'Joetastic', title: 'Joetastic Joestar\'s JoJo’s Bizarre Adventure Song Pack' },
  { name: '20-06-13_bloq-busters-vol-4-high-octane_bloq-busters', author: 'Bloq Busters', title: 'High Octane (Bloq Busters Vol. 4)' },
  { name: '20-05-22_thefatrat-music-pack_timeweaver', author: 'Timeweaver', title: 'TheFatRat Music Pack' },
  { name: '20-05-15_ramen-noodle-touhou-pack_skeelie', author: 'Skeelie', title: 'Ramen Noodle Touhou Pack' },
  { name: '20-05-01_noodle-remaster-ost-1_pixelguy', author: 'Pixelguy', title: 'Noodle Remaster OST 1' },
  { name: '20-04-18_best-k-pop-maps-vol-5_bloodcloak', author: 'Bloodcloak', title: 'Best K-Pop Maps Vol. 5' },
  { name: '20-04-12_tokyo-machine-pack_pixelguy', author: 'Pixelguy', title: 'Tokyo Machine Pack' },
  { name: '20-03-29_bloq-busters-vol-3-rhythm-soul_bloq-busters', author: 'Bloq Busters', title: 'Rhythm & Soul (Bloq Busters Vol. 3)' },
  { name: '20-03-27_idolmaster-songs-vol-1_joetastic', author: 'Joetastic', title: 'iDOLM@STER Songs Vol. 1' },
  { name: '20-03-13_pickletech-goes-to-the-movies-1980s_majorpickle-techbutterfly', author: 'MajorPickle - TechButterfly', title: 'PickleTech Goes to the Movies - 1980s' },
  { name: '20-02-08_chart-a-thon-2019_bsmg', author: 'BSMG', title: 'Chart-a-thon 2019' },
  { name: '20-01-24_noodlegames_checkthepan', author: 'Checkthepan', title: 'Noodlegames' },
  { name: '20-01-20_bloq-busters-vol-2-melodic-dubstep_bloq-busters', author: 'Bloq Busters', title: 'Melodic Dubstep (Bloq Busters Vol. 2)' },
  { name: '20-01-20_bloq-busters-vol-1-droeloe-x-jai-wolf_bloq-busters', author: 'Bloq Busters', title: 'DROELOE x Jai Wolf (Bloq Busters Vol. 1)' },
  { name: '19-12-28_punk-goes-pop-vol-1_joetastic', author: 'Joetastic', title: 'Punk Goes Pop Vol. 1' },
  { name: '19-12-19_noodlemas_cyansnow', author: 'CyanSnow', title: 'Noodlemas' },
  { name: '19-12-14_best-k-pop-maps-vol-4_n3tman', author: 'n3tman', title: 'Best K-Pop Maps Vol. 4' },
  { name: '19-12-09_christmas-with-flow_elliotttate', author: 'elliotttate', title: 'Christmas With Fantastic Flow' },
  { name: '19-12-08_pickletech-christmas-pack_majorpickle-techbutterfly', author: 'MajorPickle - TechButterfly', title: 'PickleTech Christmas Pack' },
  { name: '19-12-06_dance-dance-revolution-ddrmix_littleasi', author: 'LittleAsi', title: 'Dance Dance Revolution [DDRMIX]' },
  { name: '19-11-06_artistic-walls-vol-1_n3tman', author: 'n3tman', title: 'Artistic Walls Vol. 1' },
  { name: '19-10-30_noodleween-a-halloween-map-pack_skeelie', author: 'Skeelie', title: 'Noodleween: a Halloween map pack' },
  { name: '19-09-26_workout-with-fantastic-flow-vol-1_bloq-busters', author: 'Bloq Busters', title: 'Workout With Fantastic Flow Vol. 1' },
  { name: '19-09-14_one-saber-maps-vol-1_n3tman', author: 'n3tman', title: 'One Saber Maps Vol. 1' },
  { name: '19-09-06_best-k-pop-maps-vol-3_n3tman', author: 'n3tman', title: 'Best K-Pop Maps Vol. 3' },
  { name: '19-08-31_anniversary-song-pack_bsmg', author: 'BSMG', title: 'Anniversary Song Pack' },
  { name: '19-08-19_western-multi-difficulty-maps_redmagi', author: 'Redmagi', title: 'Western Multi-Difficulty Maps' },
  { name: '19-08-19_eastern-multi-difficulty-maps_redmagi', author: 'Redmagi', title: 'Eastern Multi-Difficulty Maps' },
  { name: '19-08-12_supercell-egoist-song-pack_uninstaller', author: 'Uninstaller', title: 'supercell / EGOIST Song Pack' },
  { name: '19-08-12_psyc0pathics-despacito-mashups_psyc0pathic', author: 'Psyc0pathic', title: 'Despacito' },
  { name: '19-06-05_twice-pack-vol-1_sotarks', author: 'Sotarks', title: 'TWICE Pack Vol. 1' },
  { name: '19-05-10_best-k-pop-maps-vol-2_n3tman', author: 'n3tman', title: 'Best K-Pop Maps Vol. 2' },
  { name: '19-04-12_songs-with-fantastic-flow-vol-5_elliotttate', author: 'elliotttate', title: 'Songs With Fantastic Flow Vol. 5' },
  { name: '19-02-23_beat-saber-goes-90s_heisenbergirl', author: 'HeisenbergIRL', title: 'Beat Saber Goes 90s' },
  { name: '19-02-21_maps-for-competitive-expert-players_hexxygonial', author: 'Hexxygonial', title: 'Excellent Maps for Competitive Expert+ Players' },
  { name: '19-02-20_best-k-pop-maps-vol-1_n3tman', author: 'n3tman', title: 'Best K-Pop Maps Vol. 1' },
  { name: '19-02-09_songs-with-fantastic-flow-vol-4_elliotttate', author: 'elliotttate', title: 'Songs With Fantastic Flow Vol. 4' },
  { name: '19-01-28_smash-bros-map-pack_todokete-and-edzo', author: 'Todokete & Edzo', title: 'Smash Bros Map Pack' },
  { name: '19-01-24_make-sabaton-great-again_msga', author: 'MSGA', title: 'Make Sabaton Great Again' },
  { name: '18-12-19_maps-for-new-players_hoppaw', author: 'Hoppaw', title: 'Maps For New Players' },
  { name: '18-11-12_the-100k-contest_bsmg', author: 'BSMG', title: 'The 100K Contest' },
  { name: '18-10-31_halloween-with-flow-vol-1_elliotttate', author: 'elliotttate', title: 'Halloween With Flow Vol. 1' },
  { name: '18-09-27_songs-with-fantastic-flow-vol-3_elliotttate', author: 'elliotttate', title: 'Songs With Fantastic Flow Vol. 3' },
  { name: '18-08-12_songs-with-fantastic-flow-vol-2_elliotttate', author: 'elliotttate', title: 'Songs With Fantastic Flow Vol. 2' },
  { name: '18-08-08_kyle-the-kirbys-collection_kyle1413', author: 'Kyle1413', title: 'Kyle The Kirby\'s Collection' },
  { name: '18-08-08_lemme-see-you-dance_bennydabeast', author: 'BennyDaBeast', title: 'Lemme See You Dance!' },
  { name: '18-08-07_workout-with-a-flow_quinn', author: 'Quinn', title: 'Workout with a flow' },
  { name: '18-08-06_songs-with-fantastic-flow-vol-1_elliotttate', author: 'elliotttate', title: 'Songs With Fantastic Flow Vol. 1' },



  /*   { name: 'maps-for-new-players', author: 'hoppaw', title: 'Maps for New Players' },
    { name: 'bsmg-anniversary-song-pack', author: 'elliotttate', title: 'BeastSaber Anniversary Pack' },
    { name: 'fantasticflowvol1', author: 'elliotttate', title: 'Songs with Fantastic Flow Vol. 1' },
    { name: 'fantasticflowvol2', author: 'elliotttate', title: 'Songs with Fantastic Flow Vol. 2' },
    { name: 'songs-with-fantastic-flow-vol-3', author: 'elliotttate', title: 'Songs with Fantastic Flow Vol. 3' },
    { name: 'songs-with-fantastic-flow-vol-4', author: 'elliotttate', title: 'Songs with Fantastic Flow Vol. 4' },
    { name: 'songs-with-fantastic-flow-vol-5', author: 'elliotttate', title: 'Songs with Fantastic Flow Vol. 5' },
    { name: 'workout-flow', author: 'Quinn2018', title: 'Workout Flow' },
    { name: 'lemme-see-you-dance', author: 'BennyDaBeast', title: 'Lemme See You Dance' },
    { name: 'best-of-kpop-vol-1', author: 'K-Pop BS Discord', title: 'Best of K-Pop Vol. 1' },
    { name: 'best-of-k-pop-vol-2', author: 'K-Pop BS Discord', title: 'Best of K-Pop Vol. 2' } */
];
